---
# "helm" version to install
helm_version: "3.6.2"

# The default "archive" will download "helm" as a ".tar.gz" file. This is
# about 2.5x smaller then "binary" but the tarball needs to be unarchived
# by the role first after downloading.
# If you specify "binary" the "helm" binary file will be downloaded. In
# contrast to the tarball the binary file is about 2.5x bigger but doesn't
# need to be unarchived by this role.
# If download file size is important for you (e.g. slow download or download
# over mobile link) stay with "archive". Otherwise "binary" might be an option.
helm_download_filetype: "binary"
# SHA256 checksum of the archve (see https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz.sha256sum)
helm_checksum_archive: "sha256:07c100849925623dc1913209cd1a30f0a9b80a5b4d6ff2153c609d11b043e262"
# SHA256 checksum of the archve (see https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz.sha256sum)
helm_checksum_archive: "sha256:f3a4be96b8a3b61b14eec1a35072e1d6e695352e7a08751775abf77861a0bf54"

# Where to install "helm" binary
helm_bin_directory: "/usr/local/bin"

# Directory to store the kubeclient archive
helm_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"

# Owner of "helm" binary
helm_owner: "root"

# Group of "helm" binary
helm_group: "root"

# Specifies the permissions of the "helm" binary
helm_binary_mode: "0755"

# Operarting system on which "helm" should run on
helm_os: "linux" # use "darwin" for MacOS X, "windows" for Windows

# Processor architecture "helm" should run on
helm_arch: "amd64" # other possible values: "386","arm64","arm","ppc64le","s390x"
